export { Producto } from './producto.model'
export { Persona } from './persona.model'
export { Usuario, RespuestaLogin } from './usuario.model'
export { TipoDocumento } from './tipodocumento.model'
export {Cargo} from './cargo.model'
export {Clientes} from './clientes.model'
export {Sucursal} from './sucursal.model'
export {Rol} from './rol.model'
export{Estado} from './estado.model'
export{MetodoPago} from './metodopago.model'
export{TipoTela} from './tipotela.model'
export {TipoComprobante} from './tipocomprobante.model'