export { PersonaService } from './persona/persona.service'
export { UsuarioService } from './usuario/usuario.service'
export { ProductoService } from './producto/producto.service'
export { TipodocumentoService } from './tipodocumento/tipodocumento.service'
export {CargoService} from './cargo/cargo.service'
export{ClientesService} from './clientes/clientes.service'
export{SucursalService} from './sucursal/sucursal.service'
export{RolService} from './rol/rol.service'
export{EstadoService} from './estado/estado.service'
export{MetodoPagoService} from './metodopago/metodopago.service'
export {TipoTelaService} from './tipotela/tipotela.service'
export {TipoComprobanteService} from './tipocomprobante/tipocomprobante.service'